/*
* generated by Xtext
*/
package it.univaq.coevolution.emfmigrate.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import it.univaq.coevolution.emfmigrate.services.EmigGrammarAccess;

public class EmigParser extends AbstractContentAssistParser {
	
	@Inject
	private EmigGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected it.univaq.coevolution.emfmigrate.ui.contentassist.antlr.internal.InternalEmigParser createParser() {
		it.univaq.coevolution.emfmigrate.ui.contentassist.antlr.internal.InternalEmigParser result = new it.univaq.coevolution.emfmigrate.ui.contentassist.antlr.internal.InternalEmigParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getMyModelAccess().getAlternatives(), "rule__MyModel__Alternatives");
					put(grammarAccess.getArtifactAccess().getTypeAlternatives_0(), "rule__Artifact__TypeAlternatives_0");
					put(grammarAccess.getOpDefAccess().getAlternatives(), "rule__OpDef__Alternatives");
					put(grammarAccess.getEPackageOpDefAccess().getAlternatives_1_0(), "rule__EPackageOpDef__Alternatives_1_0");
					put(grammarAccess.getEPackageOpDefAccess().getAlternatives_1_8(), "rule__EPackageOpDef__Alternatives_1_8");
					put(grammarAccess.getEClassOpDefAccess().getAlternatives_1_0(), "rule__EClassOpDef__Alternatives_1_0");
					put(grammarAccess.getEClassOpDefAccess().getAlternatives_1_7_1(), "rule__EClassOpDef__Alternatives_1_7_1");
					put(grammarAccess.getEAttributeOpDefAccess().getAlternatives_1_0_0(), "rule__EAttributeOpDef__Alternatives_1_0_0");
					put(grammarAccess.getEAttributeOpDefAccess().getAlternatives_1_3(), "rule__EAttributeOpDef__Alternatives_1_3");
					put(grammarAccess.getEReferenceOpDefAccess().getAlternatives_1_0_0(), "rule__EReferenceOpDef__Alternatives_1_0_0");
					put(grammarAccess.getMigratorAccess().getAlternatives(), "rule__Migrator__Alternatives");
					put(grammarAccess.getMigratorDXAccess().getAlternatives(), "rule__MigratorDX__Alternatives");
					put(grammarAccess.getStructuralFeatureAccess().getAlternatives(), "rule__StructuralFeature__Alternatives");
					put(grammarAccess.getOclFeatureAccess().getAlternatives(), "rule__OclFeature__Alternatives");
					put(grammarAccess.getOclTypeAccess().getAlternatives(), "rule__OclType__Alternatives");
					put(grammarAccess.getOclExpressionAccess().getAlternatives(), "rule__OclExpression__Alternatives");
					put(grammarAccess.getVariableDeclarationAccess().getAlternatives(), "rule__VariableDeclaration__Alternatives");
					put(grammarAccess.getIteratorExpAccess().getAlternatives_2(), "rule__IteratorExp__Alternatives_2");
					put(grammarAccess.getBooleanAccess().getAlternatives(), "rule__Boolean__Alternatives");
					put(grammarAccess.getPrimitiveTypeIdentifierAccess().getAlternatives(), "rule__PrimitiveTypeIdentifier__Alternatives");
					put(grammarAccess.getOCLReservedKeywordAccess().getAlternatives(), "rule__OCLReservedKeyword__Alternatives");
					put(grammarAccess.getOCLUnrestrictedIdentifierAccess().getAlternatives(), "rule__OCLUnrestrictedIdentifier__Alternatives");
					put(grammarAccess.getOCLPrefixOperatorAccess().getAlternatives(), "rule__OCLPrefixOperator__Alternatives");
					put(grammarAccess.getOCLInfixOperatorAccess().getAlternatives(), "rule__OCLInfixOperator__Alternatives");
					put(grammarAccess.getMigrationLibraryAccess().getGroup(), "rule__MigrationLibrary__Group__0");
					put(grammarAccess.getMigrationProgramAccess().getGroup(), "rule__MigrationProgram__Group__0");
					put(grammarAccess.getMigrationProgramAccess().getGroup_0(), "rule__MigrationProgram__Group_0__0");
					put(grammarAccess.getMigrationProgramAccess().getGroup_5(), "rule__MigrationProgram__Group_5__0");
					put(grammarAccess.getMigrationProgramAccess().getGroup_5_1(), "rule__MigrationProgram__Group_5_1__0");
					put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
					put(grammarAccess.getEPackageOpDefAccess().getGroup(), "rule__EPackageOpDef__Group__0");
					put(grammarAccess.getEPackageOpDefAccess().getGroup_0(), "rule__EPackageOpDef__Group_0__0");
					put(grammarAccess.getEPackageOpDefAccess().getGroup_1(), "rule__EPackageOpDef__Group_1__0");
					put(grammarAccess.getEClassOpDefAccess().getGroup(), "rule__EClassOpDef__Group__0");
					put(grammarAccess.getEClassOpDefAccess().getGroup_0(), "rule__EClassOpDef__Group_0__0");
					put(grammarAccess.getEClassOpDefAccess().getGroup_1(), "rule__EClassOpDef__Group_1__0");
					put(grammarAccess.getEClassOpDefAccess().getGroup_1_7(), "rule__EClassOpDef__Group_1_7__0");
					put(grammarAccess.getEAttributeOpDefAccess().getGroup(), "rule__EAttributeOpDef__Group__0");
					put(grammarAccess.getEAttributeOpDefAccess().getGroup_0(), "rule__EAttributeOpDef__Group_0__0");
					put(grammarAccess.getEAttributeOpDefAccess().getGroup_1(), "rule__EAttributeOpDef__Group_1__0");
					put(grammarAccess.getEAttributeOpDefAccess().getGroup_1_0(), "rule__EAttributeOpDef__Group_1_0__0");
					put(grammarAccess.getEAttributeOpDefAccess().getGroup_1_3_0(), "rule__EAttributeOpDef__Group_1_3_0__0");
					put(grammarAccess.getEReferenceOpDefAccess().getGroup(), "rule__EReferenceOpDef__Group__0");
					put(grammarAccess.getEReferenceOpDefAccess().getGroup_0(), "rule__EReferenceOpDef__Group_0__0");
					put(grammarAccess.getEReferenceOpDefAccess().getGroup_1(), "rule__EReferenceOpDef__Group_1__0");
					put(grammarAccess.getEReferenceOpDefAccess().getGroup_1_0(), "rule__EReferenceOpDef__Group_1_0__0");
					put(grammarAccess.getEReferenceOpDefAccess().getGroup_1_3(), "rule__EReferenceOpDef__Group_1_3__0");
					put(grammarAccess.getSetterDefAccess().getGroup(), "rule__SetterDef__Group__0");
					put(grammarAccess.getSetterDefAccess().getGroup_4(), "rule__SetterDef__Group_4__0");
					put(grammarAccess.getRewritingRuleAccess().getGroup(), "rule__RewritingRule__Group__0");
					put(grammarAccess.getRewritingRuleAccess().getGroup_0(), "rule__RewritingRule__Group_0__0");
					put(grammarAccess.getRewritingRuleAccess().getGroup_1(), "rule__RewritingRule__Group_1__0");
					put(grammarAccess.getMigratorSXAccess().getGroup(), "rule__MigratorSX__Group__0");
					put(grammarAccess.getMigratorSXAccess().getGroup_7(), "rule__MigratorSX__Group_7__0");
					put(grammarAccess.getMigratorDXAccess().getGroup_0(), "rule__MigratorDX__Group_0__0");
					put(grammarAccess.getMigratorDXAccess().getGroup_0_1(), "rule__MigratorDX__Group_0_1__0");
					put(grammarAccess.getMigratorDXAccess().getGroup_0_1_5(), "rule__MigratorDX__Group_0_1_5__0");
					put(grammarAccess.getDotNavigationObjSXAccess().getGroup(), "rule__DotNavigationObjSX__Group__0");
					put(grammarAccess.getDotNavigationObjSXAccess().getGroup_2(), "rule__DotNavigationObjSX__Group_2__0");
					put(grammarAccess.getDotNavigationObjDXAccess().getGroup(), "rule__DotNavigationObjDX__Group__0");
					put(grammarAccess.getDotNavigationObjDXAccess().getGroup_2(), "rule__DotNavigationObjDX__Group_2__0");
					put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
					put(grammarAccess.getPackageAccess().getGroup(), "rule__Package__Group__0");
					put(grammarAccess.getClassAccess().getGroup(), "rule__Class__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getReferenceAccess().getGroup(), "rule__Reference__Group__0");
					put(grammarAccess.getOclExpressionAccess().getGroup_34(), "rule__OclExpression__Group_34__0");
					put(grammarAccess.getOclFeatureDefinitionAccess().getGroup(), "rule__OclFeatureDefinition__Group__0");
					put(grammarAccess.getOclFeatureDefinitionAccess().getGroup_0(), "rule__OclFeatureDefinition__Group_0__0");
					put(grammarAccess.getOclContextDefinitionAccess().getGroup(), "rule__OclContextDefinition__Group__0");
					put(grammarAccess.getOclAttributeAccess().getGroup(), "rule__OclAttribute__Group__0");
					put(grammarAccess.getOperationAccess().getGroup(), "rule__Operation__Group__0");
					put(grammarAccess.getOperationAccess().getGroup_2(), "rule__Operation__Group_2__0");
					put(grammarAccess.getOperationAccess().getGroup_2_2(), "rule__Operation__Group_2_2__0");
					put(grammarAccess.getOclType_ImplAccess().getGroup(), "rule__OclType_Impl__Group__0");
					put(grammarAccess.getOclType_ImplAccess().getGroup_2(), "rule__OclType_Impl__Group_2__0");
					put(grammarAccess.getVariableExpAccess().getGroup(), "rule__VariableExp__Group__0");
					put(grammarAccess.getSuperExpAccess().getGroup(), "rule__SuperExp__Group__0");
					put(grammarAccess.getBagExpAccess().getGroup(), "rule__BagExp__Group__0");
					put(grammarAccess.getBagExpAccess().getGroup_3(), "rule__BagExp__Group_3__0");
					put(grammarAccess.getBagExpAccess().getGroup_3_2(), "rule__BagExp__Group_3_2__0");
					put(grammarAccess.getOrderedSetExpAccess().getGroup(), "rule__OrderedSetExp__Group__0");
					put(grammarAccess.getOrderedSetExpAccess().getGroup_3(), "rule__OrderedSetExp__Group_3__0");
					put(grammarAccess.getOrderedSetExpAccess().getGroup_3_2(), "rule__OrderedSetExp__Group_3_2__0");
					put(grammarAccess.getSequenceExpAccess().getGroup(), "rule__SequenceExp__Group__0");
					put(grammarAccess.getSequenceExpAccess().getGroup_3(), "rule__SequenceExp__Group_3__0");
					put(grammarAccess.getSequenceExpAccess().getGroup_3_2(), "rule__SequenceExp__Group_3_2__0");
					put(grammarAccess.getSetExpAccess().getGroup(), "rule__SetExp__Group__0");
					put(grammarAccess.getSetExpAccess().getGroup_3(), "rule__SetExp__Group_3__0");
					put(grammarAccess.getSetExpAccess().getGroup_3_2(), "rule__SetExp__Group_3_2__0");
					put(grammarAccess.getTupleExpAccess().getGroup(), "rule__TupleExp__Group__0");
					put(grammarAccess.getTupleExpAccess().getGroup_3(), "rule__TupleExp__Group_3__0");
					put(grammarAccess.getTupleExpAccess().getGroup_3_2(), "rule__TupleExp__Group_3_2__0");
					put(grammarAccess.getMapExpAccess().getGroup(), "rule__MapExp__Group__0");
					put(grammarAccess.getMapExpAccess().getGroup_3(), "rule__MapExp__Group_3__0");
					put(grammarAccess.getMapExpAccess().getGroup_3_2(), "rule__MapExp__Group_3_2__0");
					put(grammarAccess.getEnumLiteralExpAccess().getGroup(), "rule__EnumLiteralExp__Group__0");
					put(grammarAccess.getOclUndefinedExpAccess().getGroup(), "rule__OclUndefinedExp__Group__0");
					put(grammarAccess.getNavigationOrAttributeCallExpAccess().getGroup(), "rule__NavigationOrAttributeCallExp__Group__0");
					put(grammarAccess.getOperationCallExpAccess().getGroup(), "rule__OperationCallExp__Group__0");
					put(grammarAccess.getOperationCallExpAccess().getGroup_3(), "rule__OperationCallExp__Group_3__0");
					put(grammarAccess.getOperatorCallExpAccess().getGroup(), "rule__OperatorCallExp__Group__0");
					put(grammarAccess.getOperatorCallExpAccess().getGroup_2(), "rule__OperatorCallExp__Group_2__0");
					put(grammarAccess.getOperatorCallExpAccess().getGroup_2_3(), "rule__OperatorCallExp__Group_2_3__0");
					put(grammarAccess.getCollectionOperationCallExpAccess().getGroup(), "rule__CollectionOperationCallExp__Group__0");
					put(grammarAccess.getCollectionOperationCallExpAccess().getGroup_3(), "rule__CollectionOperationCallExp__Group_3__0");
					put(grammarAccess.getIterateExpAccess().getGroup(), "rule__IterateExp__Group__0");
					put(grammarAccess.getIterateExpAccess().getGroup_2(), "rule__IterateExp__Group_2__0");
					put(grammarAccess.getIterateExpAccess().getGroup_2_1(), "rule__IterateExp__Group_2_1__0");
					put(grammarAccess.getIteratorExpAccess().getGroup(), "rule__IteratorExp__Group__0");
					put(grammarAccess.getIteratorExpAccess().getGroup_2_0(), "rule__IteratorExp__Group_2_0__0");
					put(grammarAccess.getIteratorExpAccess().getGroup_2_0_1(), "rule__IteratorExp__Group_2_0_1__0");
					put(grammarAccess.getLetExpAccess().getGroup(), "rule__LetExp__Group__0");
					put(grammarAccess.getIfExpAccess().getGroup(), "rule__IfExp__Group__0");
					put(grammarAccess.getCollectionType_ImplAccess().getGroup(), "rule__CollectionType_Impl__Group__0");
					put(grammarAccess.getBagTypeAccess().getGroup(), "rule__BagType__Group__0");
					put(grammarAccess.getBagTypeAccess().getGroup_4(), "rule__BagType__Group_4__0");
					put(grammarAccess.getOrderedSetTypeAccess().getGroup(), "rule__OrderedSetType__Group__0");
					put(grammarAccess.getOrderedSetTypeAccess().getGroup_4(), "rule__OrderedSetType__Group_4__0");
					put(grammarAccess.getSequenceTypeAccess().getGroup(), "rule__SequenceType__Group__0");
					put(grammarAccess.getSequenceTypeAccess().getGroup_4(), "rule__SequenceType__Group_4__0");
					put(grammarAccess.getSetTypeAccess().getGroup(), "rule__SetType__Group__0");
					put(grammarAccess.getSetTypeAccess().getGroup_4(), "rule__SetType__Group_4__0");
					put(grammarAccess.getTupleTypeAccess().getGroup(), "rule__TupleType__Group__0");
					put(grammarAccess.getTupleTypeAccess().getGroup_2(), "rule__TupleType__Group_2__0");
					put(grammarAccess.getTupleTypeAccess().getGroup_2_2(), "rule__TupleType__Group_2_2__0");
					put(grammarAccess.getOclModelElementAccess().getGroup(), "rule__OclModelElement__Group__0");
					put(grammarAccess.getMapTypeAccess().getGroup(), "rule__MapType__Group__0");
					put(grammarAccess.getVariableDeclaration_ImplAccess().getGroup(), "rule__VariableDeclaration_Impl__Group__0");
					put(grammarAccess.getVariableDeclaration_ImplAccess().getGroup_2(), "rule__VariableDeclaration_Impl__Group_2__0");
					put(grammarAccess.getVariableDeclaration_ImplAccess().getGroup_2_0(), "rule__VariableDeclaration_Impl__Group_2_0__0");
					put(grammarAccess.getVariableDeclaration_ImplAccess().getGroup_2_0_3(), "rule__VariableDeclaration_Impl__Group_2_0_3__0");
					put(grammarAccess.getTuplePartAccess().getGroup(), "rule__TuplePart__Group__0");
					put(grammarAccess.getTuplePartAccess().getGroup_1(), "rule__TuplePart__Group_1__0");
					put(grammarAccess.getTuplePartAccess().getGroup_2(), "rule__TuplePart__Group_2__0");
					put(grammarAccess.getOclParameterAccess().getGroup(), "rule__OclParameter__Group__0");
					put(grammarAccess.getOclParameterAccess().getGroup_0(), "rule__OclParameter__Group_0__0");
					put(grammarAccess.getOclParameterAccess().getGroup_3(), "rule__OclParameter__Group_3__0");
					put(grammarAccess.getOclParameterAccess().getGroup_3_3(), "rule__OclParameter__Group_3_3__0");
					put(grammarAccess.getMapElementAccess().getGroup(), "rule__MapElement__Group__0");
					put(grammarAccess.getTupleTypeAttributeAccess().getGroup(), "rule__TupleTypeAttribute__Group__0");
					put(grammarAccess.getOclModelAccess().getGroup(), "rule__OclModel__Group__0");
					put(grammarAccess.getMyModelAccess().getMigrationLibAssignment_0(), "rule__MyModel__MigrationLibAssignment_0");
					put(grammarAccess.getMyModelAccess().getMigrationProgrAssignment_1(), "rule__MyModel__MigrationProgrAssignment_1");
					put(grammarAccess.getMigrationLibraryAccess().getTitleAssignment_1(), "rule__MigrationLibrary__TitleAssignment_1");
					put(grammarAccess.getMigrationLibraryAccess().getRulesAssignment_3(), "rule__MigrationLibrary__RulesAssignment_3");
					put(grammarAccess.getMigrationProgramAccess().getLibsAssignment_0_1(), "rule__MigrationProgram__LibsAssignment_0_1");
					put(grammarAccess.getMigrationProgramAccess().getMigrAssignment_1(), "rule__MigrationProgram__MigrAssignment_1");
					put(grammarAccess.getMigrationProgramAccess().getTypeArtAssignment_2(), "rule__MigrationProgram__TypeArtAssignment_2");
					put(grammarAccess.getMigrationProgramAccess().getNameAssignment_3(), "rule__MigrationProgram__NameAssignment_3");
					put(grammarAccess.getMigrationProgramAccess().getTransformationPackageAssignment_5_0(), "rule__MigrationProgram__TransformationPackageAssignment_5_0");
					put(grammarAccess.getMigrationProgramAccess().getTransformationPackageAssignment_5_1_1(), "rule__MigrationProgram__TransformationPackageAssignment_5_1_1");
					put(grammarAccess.getMigrationProgramAccess().getDeltaAssignment_7(), "rule__MigrationProgram__DeltaAssignment_7");
					put(grammarAccess.getMigrationProgramAccess().getRulesAssignment_9(), "rule__MigrationProgram__RulesAssignment_9");
					put(grammarAccess.getArtifactAccess().getTypeAssignment(), "rule__Artifact__TypeAssignment");
					put(grammarAccess.getRuleAccess().getNameAssignment_1(), "rule__Rule__NameAssignment_1");
					put(grammarAccess.getRuleAccess().getFilterAssignment_3(), "rule__Rule__FilterAssignment_3");
					put(grammarAccess.getRuleAccess().getRewritingRulesAssignment_6(), "rule__Rule__RewritingRulesAssignment_6");
					put(grammarAccess.getEPackageOpDefAccess().getVarAssignment_0_1(), "rule__EPackageOpDef__VarAssignment_0_1");
					put(grammarAccess.getEPackageOpDefAccess().getOpAssignment_1_0_0(), "rule__EPackageOpDef__OpAssignment_1_0_0");
					put(grammarAccess.getEPackageOpDefAccess().getOpAssignment_1_0_1(), "rule__EPackageOpDef__OpAssignment_1_0_1");
					put(grammarAccess.getEPackageOpDefAccess().getOpAssignment_1_0_2(), "rule__EPackageOpDef__OpAssignment_1_0_2");
					put(grammarAccess.getEPackageOpDefAccess().getRefAssignment_1_2(), "rule__EPackageOpDef__RefAssignment_1_2");
					put(grammarAccess.getEPackageOpDefAccess().getSettersAssignment_1_8_0(), "rule__EPackageOpDef__SettersAssignment_1_8_0");
					put(grammarAccess.getEPackageOpDefAccess().getClassesAssignment_1_8_1(), "rule__EPackageOpDef__ClassesAssignment_1_8_1");
					put(grammarAccess.getEClassOpDefAccess().getVarAssignment_0_1(), "rule__EClassOpDef__VarAssignment_0_1");
					put(grammarAccess.getEClassOpDefAccess().getOpAssignment_1_0_0(), "rule__EClassOpDef__OpAssignment_1_0_0");
					put(grammarAccess.getEClassOpDefAccess().getOpAssignment_1_0_1(), "rule__EClassOpDef__OpAssignment_1_0_1");
					put(grammarAccess.getEClassOpDefAccess().getOpAssignment_1_0_2(), "rule__EClassOpDef__OpAssignment_1_0_2");
					put(grammarAccess.getEClassOpDefAccess().getRefAssignment_1_2(), "rule__EClassOpDef__RefAssignment_1_2");
					put(grammarAccess.getEClassOpDefAccess().getSettersAssignment_1_7_1_0(), "rule__EClassOpDef__SettersAssignment_1_7_1_0");
					put(grammarAccess.getEClassOpDefAccess().getAttributesAssignment_1_7_1_1(), "rule__EClassOpDef__AttributesAssignment_1_7_1_1");
					put(grammarAccess.getEClassOpDefAccess().getReferencesAssignment_1_7_1_2(), "rule__EClassOpDef__ReferencesAssignment_1_7_1_2");
					put(grammarAccess.getEAttributeOpDefAccess().getVarAssignment_0_1(), "rule__EAttributeOpDef__VarAssignment_0_1");
					put(grammarAccess.getEAttributeOpDefAccess().getOpAssignment_1_0_0_0(), "rule__EAttributeOpDef__OpAssignment_1_0_0_0");
					put(grammarAccess.getEAttributeOpDefAccess().getOpAssignment_1_0_0_1(), "rule__EAttributeOpDef__OpAssignment_1_0_0_1");
					put(grammarAccess.getEAttributeOpDefAccess().getOpAssignment_1_0_0_2(), "rule__EAttributeOpDef__OpAssignment_1_0_0_2");
					put(grammarAccess.getEAttributeOpDefAccess().getRefAssignment_1_0_2(), "rule__EAttributeOpDef__RefAssignment_1_0_2");
					put(grammarAccess.getEAttributeOpDefAccess().getSettersAssignment_1_3_0_1(), "rule__EAttributeOpDef__SettersAssignment_1_3_0_1");
					put(grammarAccess.getEReferenceOpDefAccess().getVarAssignment_0_1(), "rule__EReferenceOpDef__VarAssignment_0_1");
					put(grammarAccess.getEReferenceOpDefAccess().getOpAssignment_1_0_0_0(), "rule__EReferenceOpDef__OpAssignment_1_0_0_0");
					put(grammarAccess.getEReferenceOpDefAccess().getOpAssignment_1_0_0_1(), "rule__EReferenceOpDef__OpAssignment_1_0_0_1");
					put(grammarAccess.getEReferenceOpDefAccess().getOpAssignment_1_0_0_2(), "rule__EReferenceOpDef__OpAssignment_1_0_0_2");
					put(grammarAccess.getEReferenceOpDefAccess().getRefAssignment_1_0_2(), "rule__EReferenceOpDef__RefAssignment_1_0_2");
					put(grammarAccess.getEReferenceOpDefAccess().getSettersAssignment_1_3_1(), "rule__EReferenceOpDef__SettersAssignment_1_3_1");
					put(grammarAccess.getSetterDefAccess().getMetafeatureAssignment_1(), "rule__SetterDef__MetafeatureAssignment_1");
					put(grammarAccess.getSetterDefAccess().getOperatorAssignment_2(), "rule__SetterDef__OperatorAssignment_2");
					put(grammarAccess.getSetterDefAccess().getParAssignment_3(), "rule__SetterDef__ParAssignment_3");
					put(grammarAccess.getSetterDefAccess().getParAssignment_4_1(), "rule__SetterDef__ParAssignment_4_1");
					put(grammarAccess.getRewritingRuleAccess().getMigratorsSXAssignment_0_0(), "rule__RewritingRule__MigratorsSXAssignment_0_0");
					put(grammarAccess.getRewritingRuleAccess().getMigratorDXAssignment_0_2(), "rule__RewritingRule__MigratorDXAssignment_0_2");
					put(grammarAccess.getRewritingRuleAccess().getMigratorSXAssignment_1_1(), "rule__RewritingRule__MigratorSXAssignment_1_1");
					put(grammarAccess.getRewritingRuleAccess().getMigratorDXAssignment_1_3(), "rule__RewritingRule__MigratorDXAssignment_1_3");
					put(grammarAccess.getMigratorSXAccess().getNameAssignment_1(), "rule__MigratorSX__NameAssignment_1");
					put(grammarAccess.getMigratorSXAccess().getElementSXAssignment_3(), "rule__MigratorSX__ElementSXAssignment_3");
					put(grammarAccess.getMigratorSXAccess().getFilterSXAssignment_6(), "rule__MigratorSX__FilterSXAssignment_6");
					put(grammarAccess.getMigratorSXAccess().getFilterSXAssignment_7_1(), "rule__MigratorSX__FilterSXAssignment_7_1");
					put(grammarAccess.getMigratorDXAccess().getNameAssignment_0_1_0(), "rule__MigratorDX__NameAssignment_0_1_0");
					put(grammarAccess.getMigratorDXAccess().getElementDXAssignment_0_1_2(), "rule__MigratorDX__ElementDXAssignment_0_1_2");
					put(grammarAccess.getMigratorDXAccess().getFilterDXAssignment_0_1_4(), "rule__MigratorDX__FilterDXAssignment_0_1_4");
					put(grammarAccess.getMigratorDXAccess().getFilterDXAssignment_0_1_5_1(), "rule__MigratorDX__FilterDXAssignment_0_1_5_1");
					put(grammarAccess.getFilterMigratorAccess().getSpecificationAssignment(), "rule__FilterMigrator__SpecificationAssignment");
					put(grammarAccess.getDotNavigationObjSXAccess().getObjAssignment_1(), "rule__DotNavigationObjSX__ObjAssignment_1");
					put(grammarAccess.getDotNavigationObjSXAccess().getRefAssignment_2_1(), "rule__DotNavigationObjSX__RefAssignment_2_1");
					put(grammarAccess.getDotNavigationObjDXAccess().getObjAssignment_1(), "rule__DotNavigationObjDX__ObjAssignment_1");
					put(grammarAccess.getDotNavigationObjDXAccess().getRefAssignment_2_1(), "rule__DotNavigationObjDX__RefAssignment_2_1");
					put(grammarAccess.getParameterAccess().getNameAssignment_1(), "rule__Parameter__NameAssignment_1");
					put(grammarAccess.getPackageAccess().getNameAssignment_1(), "rule__Package__NameAssignment_1");
					put(grammarAccess.getClassAccess().getNameAssignment_1(), "rule__Class__NameAssignment_1");
					put(grammarAccess.getAttributeAccess().getNameAssignment_1(), "rule__Attribute__NameAssignment_1");
					put(grammarAccess.getReferenceAccess().getNameAssignment_1(), "rule__Reference__NameAssignment_1");
					put(grammarAccess.getOclFeatureDefinitionAccess().getContext_Assignment_0_1(), "rule__OclFeatureDefinition__Context_Assignment_0_1");
					put(grammarAccess.getOclFeatureDefinitionAccess().getFeatureAssignment_3(), "rule__OclFeatureDefinition__FeatureAssignment_3");
					put(grammarAccess.getOclContextDefinitionAccess().getContext_Assignment_1(), "rule__OclContextDefinition__Context_Assignment_1");
					put(grammarAccess.getOclAttributeAccess().getNameAssignment_0(), "rule__OclAttribute__NameAssignment_0");
					put(grammarAccess.getOclAttributeAccess().getTypeAssignment_2(), "rule__OclAttribute__TypeAssignment_2");
					put(grammarAccess.getOclAttributeAccess().getInitExpressionAssignment_4(), "rule__OclAttribute__InitExpressionAssignment_4");
					put(grammarAccess.getOperationAccess().getNameAssignment_0(), "rule__Operation__NameAssignment_0");
					put(grammarAccess.getOperationAccess().getParametersAssignment_2_1(), "rule__Operation__ParametersAssignment_2_1");
					put(grammarAccess.getOperationAccess().getParametersAssignment_2_2_1(), "rule__Operation__ParametersAssignment_2_2_1");
					put(grammarAccess.getOperationAccess().getReturnTypeAssignment_5(), "rule__Operation__ReturnTypeAssignment_5");
					put(grammarAccess.getOperationAccess().getBodyAssignment_6(), "rule__Operation__BodyAssignment_6");
					put(grammarAccess.getOclType_ImplAccess().getNameAssignment_1(), "rule__OclType_Impl__NameAssignment_1");
					put(grammarAccess.getOclType_ImplAccess().getTypeAssignment_2_1(), "rule__OclType_Impl__TypeAssignment_2_1");
					put(grammarAccess.getVariableExpAccess().getReferredVariableAssignment_1(), "rule__VariableExp__ReferredVariableAssignment_1");
					put(grammarAccess.getStringExpAccess().getStringSymbolAssignment(), "rule__StringExp__StringSymbolAssignment");
					put(grammarAccess.getBooleanExpAccess().getBooleanSymbolAssignment(), "rule__BooleanExp__BooleanSymbolAssignment");
					put(grammarAccess.getRealExpAccess().getRealSymbolAssignment(), "rule__RealExp__RealSymbolAssignment");
					put(grammarAccess.getIntegerExpAccess().getIntegerSymbolAssignment(), "rule__IntegerExp__IntegerSymbolAssignment");
					put(grammarAccess.getBagExpAccess().getElementsAssignment_3_1(), "rule__BagExp__ElementsAssignment_3_1");
					put(grammarAccess.getBagExpAccess().getElementsAssignment_3_2_1(), "rule__BagExp__ElementsAssignment_3_2_1");
					put(grammarAccess.getOrderedSetExpAccess().getElementsAssignment_3_1(), "rule__OrderedSetExp__ElementsAssignment_3_1");
					put(grammarAccess.getOrderedSetExpAccess().getElementsAssignment_3_2_1(), "rule__OrderedSetExp__ElementsAssignment_3_2_1");
					put(grammarAccess.getSequenceExpAccess().getElementsAssignment_3_1(), "rule__SequenceExp__ElementsAssignment_3_1");
					put(grammarAccess.getSequenceExpAccess().getElementsAssignment_3_2_1(), "rule__SequenceExp__ElementsAssignment_3_2_1");
					put(grammarAccess.getSetExpAccess().getElementsAssignment_3_1(), "rule__SetExp__ElementsAssignment_3_1");
					put(grammarAccess.getSetExpAccess().getElementsAssignment_3_2_1(), "rule__SetExp__ElementsAssignment_3_2_1");
					put(grammarAccess.getTupleExpAccess().getTuplePartAssignment_3_1(), "rule__TupleExp__TuplePartAssignment_3_1");
					put(grammarAccess.getTupleExpAccess().getTuplePartAssignment_3_2_1(), "rule__TupleExp__TuplePartAssignment_3_2_1");
					put(grammarAccess.getMapExpAccess().getElementsAssignment_3_1(), "rule__MapExp__ElementsAssignment_3_1");
					put(grammarAccess.getMapExpAccess().getElementsAssignment_3_2_1(), "rule__MapExp__ElementsAssignment_3_2_1");
					put(grammarAccess.getEnumLiteralExpAccess().getNameAssignment_1(), "rule__EnumLiteralExp__NameAssignment_1");
					put(grammarAccess.getNavigationOrAttributeCallExpAccess().getNameAssignment_2(), "rule__NavigationOrAttributeCallExp__NameAssignment_2");
					put(grammarAccess.getOperationCallExpAccess().getOperationNameAssignment_0(), "rule__OperationCallExp__OperationNameAssignment_0");
					put(grammarAccess.getOperationCallExpAccess().getArgumentsAssignment_2(), "rule__OperationCallExp__ArgumentsAssignment_2");
					put(grammarAccess.getOperationCallExpAccess().getArgumentsAssignment_3_1(), "rule__OperationCallExp__ArgumentsAssignment_3_1");
					put(grammarAccess.getOperatorCallExpAccess().getOperationNameAssignment_0(), "rule__OperatorCallExp__OperationNameAssignment_0");
					put(grammarAccess.getOperatorCallExpAccess().getArgumentsAssignment_2_2(), "rule__OperatorCallExp__ArgumentsAssignment_2_2");
					put(grammarAccess.getOperatorCallExpAccess().getArgumentsAssignment_2_3_1(), "rule__OperatorCallExp__ArgumentsAssignment_2_3_1");
					put(grammarAccess.getCollectionOperationCallExpAccess().getOperationNameAssignment_0(), "rule__CollectionOperationCallExp__OperationNameAssignment_0");
					put(grammarAccess.getCollectionOperationCallExpAccess().getArgumentsAssignment_2(), "rule__CollectionOperationCallExp__ArgumentsAssignment_2");
					put(grammarAccess.getCollectionOperationCallExpAccess().getArgumentsAssignment_3_1(), "rule__CollectionOperationCallExp__ArgumentsAssignment_3_1");
					put(grammarAccess.getIterateExpAccess().getIteratorsAssignment_2_0(), "rule__IterateExp__IteratorsAssignment_2_0");
					put(grammarAccess.getIterateExpAccess().getIteratorsAssignment_2_1_1(), "rule__IterateExp__IteratorsAssignment_2_1_1");
					put(grammarAccess.getIterateExpAccess().getResultAssignment_4(), "rule__IterateExp__ResultAssignment_4");
					put(grammarAccess.getIterateExpAccess().getBodyAssignment_6(), "rule__IterateExp__BodyAssignment_6");
					put(grammarAccess.getIteratorExpAccess().getNameAssignment_0(), "rule__IteratorExp__NameAssignment_0");
					put(grammarAccess.getIteratorExpAccess().getIteratorsAssignment_2_0_0(), "rule__IteratorExp__IteratorsAssignment_2_0_0");
					put(grammarAccess.getIteratorExpAccess().getIteratorsAssignment_2_0_1_1(), "rule__IteratorExp__IteratorsAssignment_2_0_1_1");
					put(grammarAccess.getIteratorExpAccess().getBodyAssignment_2_1(), "rule__IteratorExp__BodyAssignment_2_1");
					put(grammarAccess.getLetExpAccess().getVariableAssignment_1(), "rule__LetExp__VariableAssignment_1");
					put(grammarAccess.getLetExpAccess().getIn_Assignment_3(), "rule__LetExp__In_Assignment_3");
					put(grammarAccess.getIfExpAccess().getConditionAssignment_1(), "rule__IfExp__ConditionAssignment_1");
					put(grammarAccess.getIfExpAccess().getThenExpressionAssignment_3(), "rule__IfExp__ThenExpressionAssignment_3");
					put(grammarAccess.getIfExpAccess().getElseExpressionAssignment_5(), "rule__IfExp__ElseExpressionAssignment_5");
					put(grammarAccess.getCollectionType_ImplAccess().getElementTypeAssignment_2(), "rule__CollectionType_Impl__ElementTypeAssignment_2");
					put(grammarAccess.getBagTypeAccess().getNameAssignment_3(), "rule__BagType__NameAssignment_3");
					put(grammarAccess.getBagTypeAccess().getTypeAssignment_4_1(), "rule__BagType__TypeAssignment_4_1");
					put(grammarAccess.getBagTypeAccess().getElementTypeAssignment_6(), "rule__BagType__ElementTypeAssignment_6");
					put(grammarAccess.getOrderedSetTypeAccess().getNameAssignment_3(), "rule__OrderedSetType__NameAssignment_3");
					put(grammarAccess.getOrderedSetTypeAccess().getTypeAssignment_4_1(), "rule__OrderedSetType__TypeAssignment_4_1");
					put(grammarAccess.getOrderedSetTypeAccess().getElementTypeAssignment_6(), "rule__OrderedSetType__ElementTypeAssignment_6");
					put(grammarAccess.getSequenceTypeAccess().getNameAssignment_3(), "rule__SequenceType__NameAssignment_3");
					put(grammarAccess.getSequenceTypeAccess().getTypeAssignment_4_1(), "rule__SequenceType__TypeAssignment_4_1");
					put(grammarAccess.getSequenceTypeAccess().getElementTypeAssignment_6(), "rule__SequenceType__ElementTypeAssignment_6");
					put(grammarAccess.getSetTypeAccess().getNameAssignment_3(), "rule__SetType__NameAssignment_3");
					put(grammarAccess.getSetTypeAccess().getTypeAssignment_4_1(), "rule__SetType__TypeAssignment_4_1");
					put(grammarAccess.getSetTypeAccess().getElementTypeAssignment_6(), "rule__SetType__ElementTypeAssignment_6");
					put(grammarAccess.getTupleTypeAccess().getAttributesAssignment_2_1(), "rule__TupleType__AttributesAssignment_2_1");
					put(grammarAccess.getTupleTypeAccess().getAttributesAssignment_2_2_1(), "rule__TupleType__AttributesAssignment_2_2_1");
					put(grammarAccess.getOclModelElementAccess().getModelAssignment_0(), "rule__OclModelElement__ModelAssignment_0");
					put(grammarAccess.getOclModelElementAccess().getNameAssignment_2(), "rule__OclModelElement__NameAssignment_2");
					put(grammarAccess.getMapTypeAccess().getKeyTypeAssignment_2(), "rule__MapType__KeyTypeAssignment_2");
					put(grammarAccess.getMapTypeAccess().getValueTypeAssignment_4(), "rule__MapType__ValueTypeAssignment_4");
					put(grammarAccess.getVariableDeclaration_ImplAccess().getVarNameAssignment_1(), "rule__VariableDeclaration_Impl__VarNameAssignment_1");
					put(grammarAccess.getVariableDeclaration_ImplAccess().getVariableExpAssignment_2_0_2(), "rule__VariableDeclaration_Impl__VariableExpAssignment_2_0_2");
					put(grammarAccess.getVariableDeclaration_ImplAccess().getVariableExpAssignment_2_0_3_1(), "rule__VariableDeclaration_Impl__VariableExpAssignment_2_0_3_1");
					put(grammarAccess.getVariableDeclaration_ImplAccess().getTypeAssignment_2_1(), "rule__VariableDeclaration_Impl__TypeAssignment_2_1");
					put(grammarAccess.getVariableDeclaration_ImplAccess().getInitExpressionAssignment_2_3(), "rule__VariableDeclaration_Impl__InitExpressionAssignment_2_3");
					put(grammarAccess.getTuplePartAccess().getVarNameAssignment_0(), "rule__TuplePart__VarNameAssignment_0");
					put(grammarAccess.getTuplePartAccess().getTypeAssignment_1_1(), "rule__TuplePart__TypeAssignment_1_1");
					put(grammarAccess.getTuplePartAccess().getInitExpressionAssignment_2_1(), "rule__TuplePart__InitExpressionAssignment_2_1");
					put(grammarAccess.getIteratorAccess().getVarNameAssignment(), "rule__Iterator__VarNameAssignment");
					put(grammarAccess.getOclParameterAccess().getIdAssignment_0_1(), "rule__OclParameter__IdAssignment_0_1");
					put(grammarAccess.getOclParameterAccess().getVarNameAssignment_1(), "rule__OclParameter__VarNameAssignment_1");
					put(grammarAccess.getOclParameterAccess().getVariableExpAssignment_3_2(), "rule__OclParameter__VariableExpAssignment_3_2");
					put(grammarAccess.getOclParameterAccess().getVariableExpAssignment_3_3_1(), "rule__OclParameter__VariableExpAssignment_3_3_1");
					put(grammarAccess.getOclParameterAccess().getTypeAssignment_4(), "rule__OclParameter__TypeAssignment_4");
					put(grammarAccess.getOclParameterAccess().getInitExpressionAssignment_6(), "rule__OclParameter__InitExpressionAssignment_6");
					put(grammarAccess.getMapElementAccess().getKeyAssignment_1(), "rule__MapElement__KeyAssignment_1");
					put(grammarAccess.getMapElementAccess().getValueAssignment_3(), "rule__MapElement__ValueAssignment_3");
					put(grammarAccess.getTupleTypeAttributeAccess().getNameAssignment_0(), "rule__TupleTypeAttribute__NameAssignment_0");
					put(grammarAccess.getTupleTypeAttributeAccess().getTypeAssignment_2(), "rule__TupleTypeAttribute__TypeAssignment_2");
					put(grammarAccess.getOclModelAccess().getNameAssignment_0(), "rule__OclModel__NameAssignment_0");
					put(grammarAccess.getOclModelAccess().getMetamodelAssignment_2(), "rule__OclModel__MetamodelAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			it.univaq.coevolution.emfmigrate.ui.contentassist.antlr.internal.InternalEmigParser typedParser = (it.univaq.coevolution.emfmigrate.ui.contentassist.antlr.internal.InternalEmigParser) parser;
			typedParser.entryRuleMyModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public EmigGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EmigGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
