/*
 * generated by Xtext
 */
package it.univaq.coevolution.emfmigrate;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EmigRuntimeModule extends it.univaq.coevolution.emfmigrate.AbstractEmigRuntimeModule {

}
