/*
* generated by Xtext
*/
package it.univaq.coevolution;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MigrationUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return it.univaq.coevolution.ui.internal.MigrationActivator.getInstance().getInjector("it.univaq.coevolution.Migration");
	}
	
}
