/*
* generated by Xtext
*/
package it.univaq.coevolution.emfmigrate.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EmigAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("it/univaq/coevolution/emfmigrate/parser/antlr/internal/InternalEmig.tokens");
	}
}
