/*
* generated by Xtext
*/
package it.univaq.coevolution.differences.edelta.ui.contentassist;

import it.univaq.coevolution.differences.edelta.ui.contentassist.AbstractEDeltaLangProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class EDeltaLangProposalProvider extends AbstractEDeltaLangProposalProvider {

}
