/*
* generated by Xtext
*/
package it.univaq.coevolution.emfmigrate.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import it.univaq.coevolution.emfmigrate.services.EmigGrammarAccess;

public class EmigParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EmigGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected it.univaq.coevolution.emfmigrate.parser.antlr.internal.InternalEmigParser createParser(XtextTokenStream stream) {
		return new it.univaq.coevolution.emfmigrate.parser.antlr.internal.InternalEmigParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "MyModel";
	}
	
	public EmigGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EmigGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
