/*
 * generated by Xtext
 */
package it.univaq.coevolution.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MigrationUiModule extends it.univaq.coevolution.ui.AbstractMigrationUiModule {
	public MigrationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
