/*
* generated by Xtext
*/
package it.univaq.coevolution.emfmigrate.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import it.univaq.coevolution.emfmigrate.services.EmigGrammarAccess;

public class EmigParser extends AbstractContentAssistParser {
	
	@Inject
	private EmigGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected it.univaq.coevolution.emfmigrate.ui.contentassist.antlr.internal.InternalEmigParser createParser() {
		it.univaq.coevolution.emfmigrate.ui.contentassist.antlr.internal.InternalEmigParser result = new it.univaq.coevolution.emfmigrate.ui.contentassist.antlr.internal.InternalEmigParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getMyModelAccess().getAlternatives(), "rule__MyModel__Alternatives");
					put(grammarAccess.getArtifactAccess().getTypeAlternatives_0(), "rule__Artifact__TypeAlternatives_0");
					put(grammarAccess.getOpDefAccess().getAlternatives(), "rule__OpDef__Alternatives");
					put(grammarAccess.getEPackageOpDefAccess().getAlternatives_1_0(), "rule__EPackageOpDef__Alternatives_1_0");
					put(grammarAccess.getEPackageOpDefAccess().getAlternatives_1_8(), "rule__EPackageOpDef__Alternatives_1_8");
					put(grammarAccess.getEClassOpDefAccess().getAlternatives_1_0(), "rule__EClassOpDef__Alternatives_1_0");
					put(grammarAccess.getEClassOpDefAccess().getAlternatives_1_7_1(), "rule__EClassOpDef__Alternatives_1_7_1");
					put(grammarAccess.getEAttributeOpDefAccess().getAlternatives_1_0_0(), "rule__EAttributeOpDef__Alternatives_1_0_0");
					put(grammarAccess.getEAttributeOpDefAccess().getAlternatives_1_3(), "rule__EAttributeOpDef__Alternatives_1_3");
					put(grammarAccess.getEReferenceOpDefAccess().getAlternatives_1_0_0(), "rule__EReferenceOpDef__Alternatives_1_0_0");
					put(grammarAccess.getMigratorAccess().getAlternatives(), "rule__Migrator__Alternatives");
					put(grammarAccess.getMigratorDXAccess().getAlternatives(), "rule__MigratorDX__Alternatives");
					put(grammarAccess.getStructuralFeatureAccess().getAlternatives(), "rule__StructuralFeature__Alternatives");
					put(grammarAccess.getMigrationLibraryAccess().getGroup(), "rule__MigrationLibrary__Group__0");
					put(grammarAccess.getMigrationProgramAccess().getGroup(), "rule__MigrationProgram__Group__0");
					put(grammarAccess.getMigrationProgramAccess().getGroup_0(), "rule__MigrationProgram__Group_0__0");
					put(grammarAccess.getMigrationProgramAccess().getGroup_5(), "rule__MigrationProgram__Group_5__0");
					put(grammarAccess.getMigrationProgramAccess().getGroup_5_1(), "rule__MigrationProgram__Group_5_1__0");
					put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
					put(grammarAccess.getEPackageOpDefAccess().getGroup(), "rule__EPackageOpDef__Group__0");
					put(grammarAccess.getEPackageOpDefAccess().getGroup_0(), "rule__EPackageOpDef__Group_0__0");
					put(grammarAccess.getEPackageOpDefAccess().getGroup_1(), "rule__EPackageOpDef__Group_1__0");
					put(grammarAccess.getEClassOpDefAccess().getGroup(), "rule__EClassOpDef__Group__0");
					put(grammarAccess.getEClassOpDefAccess().getGroup_0(), "rule__EClassOpDef__Group_0__0");
					put(grammarAccess.getEClassOpDefAccess().getGroup_1(), "rule__EClassOpDef__Group_1__0");
					put(grammarAccess.getEClassOpDefAccess().getGroup_1_7(), "rule__EClassOpDef__Group_1_7__0");
					put(grammarAccess.getEAttributeOpDefAccess().getGroup(), "rule__EAttributeOpDef__Group__0");
					put(grammarAccess.getEAttributeOpDefAccess().getGroup_0(), "rule__EAttributeOpDef__Group_0__0");
					put(grammarAccess.getEAttributeOpDefAccess().getGroup_1(), "rule__EAttributeOpDef__Group_1__0");
					put(grammarAccess.getEAttributeOpDefAccess().getGroup_1_0(), "rule__EAttributeOpDef__Group_1_0__0");
					put(grammarAccess.getEAttributeOpDefAccess().getGroup_1_3_0(), "rule__EAttributeOpDef__Group_1_3_0__0");
					put(grammarAccess.getEReferenceOpDefAccess().getGroup(), "rule__EReferenceOpDef__Group__0");
					put(grammarAccess.getEReferenceOpDefAccess().getGroup_0(), "rule__EReferenceOpDef__Group_0__0");
					put(grammarAccess.getEReferenceOpDefAccess().getGroup_1(), "rule__EReferenceOpDef__Group_1__0");
					put(grammarAccess.getEReferenceOpDefAccess().getGroup_1_0(), "rule__EReferenceOpDef__Group_1_0__0");
					put(grammarAccess.getEReferenceOpDefAccess().getGroup_1_3(), "rule__EReferenceOpDef__Group_1_3__0");
					put(grammarAccess.getSetterDefAccess().getGroup(), "rule__SetterDef__Group__0");
					put(grammarAccess.getSetterDefAccess().getGroup_4(), "rule__SetterDef__Group_4__0");
					put(grammarAccess.getRewritingRuleAccess().getGroup(), "rule__RewritingRule__Group__0");
					put(grammarAccess.getRewritingRuleAccess().getGroup_0(), "rule__RewritingRule__Group_0__0");
					put(grammarAccess.getRewritingRuleAccess().getGroup_1(), "rule__RewritingRule__Group_1__0");
					put(grammarAccess.getMigratorSXAccess().getGroup(), "rule__MigratorSX__Group__0");
					put(grammarAccess.getMigratorSXAccess().getGroup_7(), "rule__MigratorSX__Group_7__0");
					put(grammarAccess.getMigratorDXAccess().getGroup_0(), "rule__MigratorDX__Group_0__0");
					put(grammarAccess.getMigratorDXAccess().getGroup_0_1(), "rule__MigratorDX__Group_0_1__0");
					put(grammarAccess.getMigratorDXAccess().getGroup_0_1_5(), "rule__MigratorDX__Group_0_1_5__0");
					put(grammarAccess.getFilterMigratorAccess().getGroup(), "rule__FilterMigrator__Group__0");
					put(grammarAccess.getDotNavigationObjSXAccess().getGroup(), "rule__DotNavigationObjSX__Group__0");
					put(grammarAccess.getDotNavigationObjSXAccess().getGroup_2(), "rule__DotNavigationObjSX__Group_2__0");
					put(grammarAccess.getDotNavigationObjDXAccess().getGroup(), "rule__DotNavigationObjDX__Group__0");
					put(grammarAccess.getDotNavigationObjDXAccess().getGroup_2(), "rule__DotNavigationObjDX__Group_2__0");
					put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
					put(grammarAccess.getPackageAccess().getGroup(), "rule__Package__Group__0");
					put(grammarAccess.getClassAccess().getGroup(), "rule__Class__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getReferenceAccess().getGroup(), "rule__Reference__Group__0");
					put(grammarAccess.getMyModelAccess().getMigrationLibAssignment_0(), "rule__MyModel__MigrationLibAssignment_0");
					put(grammarAccess.getMyModelAccess().getMigrationProgrAssignment_1(), "rule__MyModel__MigrationProgrAssignment_1");
					put(grammarAccess.getMigrationLibraryAccess().getTitleAssignment_1(), "rule__MigrationLibrary__TitleAssignment_1");
					put(grammarAccess.getMigrationLibraryAccess().getRulesAssignment_3(), "rule__MigrationLibrary__RulesAssignment_3");
					put(grammarAccess.getMigrationProgramAccess().getLibsAssignment_0_1(), "rule__MigrationProgram__LibsAssignment_0_1");
					put(grammarAccess.getMigrationProgramAccess().getMigrAssignment_1(), "rule__MigrationProgram__MigrAssignment_1");
					put(grammarAccess.getMigrationProgramAccess().getTypeArtAssignment_2(), "rule__MigrationProgram__TypeArtAssignment_2");
					put(grammarAccess.getMigrationProgramAccess().getNameAssignment_3(), "rule__MigrationProgram__NameAssignment_3");
					put(grammarAccess.getMigrationProgramAccess().getTransformationPackageAssignment_5_0(), "rule__MigrationProgram__TransformationPackageAssignment_5_0");
					put(grammarAccess.getMigrationProgramAccess().getTransformationPackageAssignment_5_1_1(), "rule__MigrationProgram__TransformationPackageAssignment_5_1_1");
					put(grammarAccess.getMigrationProgramAccess().getDeltaAssignment_7(), "rule__MigrationProgram__DeltaAssignment_7");
					put(grammarAccess.getMigrationProgramAccess().getRulesAssignment_9(), "rule__MigrationProgram__RulesAssignment_9");
					put(grammarAccess.getArtifactAccess().getTypeAssignment(), "rule__Artifact__TypeAssignment");
					put(grammarAccess.getRuleAccess().getNameAssignment_1(), "rule__Rule__NameAssignment_1");
					put(grammarAccess.getRuleAccess().getFilterAssignment_3(), "rule__Rule__FilterAssignment_3");
					put(grammarAccess.getRuleAccess().getRewritingRulesAssignment_6(), "rule__Rule__RewritingRulesAssignment_6");
					put(grammarAccess.getEPackageOpDefAccess().getVarAssignment_0_1(), "rule__EPackageOpDef__VarAssignment_0_1");
					put(grammarAccess.getEPackageOpDefAccess().getOpAssignment_1_0_0(), "rule__EPackageOpDef__OpAssignment_1_0_0");
					put(grammarAccess.getEPackageOpDefAccess().getOpAssignment_1_0_1(), "rule__EPackageOpDef__OpAssignment_1_0_1");
					put(grammarAccess.getEPackageOpDefAccess().getOpAssignment_1_0_2(), "rule__EPackageOpDef__OpAssignment_1_0_2");
					put(grammarAccess.getEPackageOpDefAccess().getRefAssignment_1_2(), "rule__EPackageOpDef__RefAssignment_1_2");
					put(grammarAccess.getEPackageOpDefAccess().getSettersAssignment_1_8_0(), "rule__EPackageOpDef__SettersAssignment_1_8_0");
					put(grammarAccess.getEPackageOpDefAccess().getClassesAssignment_1_8_1(), "rule__EPackageOpDef__ClassesAssignment_1_8_1");
					put(grammarAccess.getEClassOpDefAccess().getVarAssignment_0_1(), "rule__EClassOpDef__VarAssignment_0_1");
					put(grammarAccess.getEClassOpDefAccess().getOpAssignment_1_0_0(), "rule__EClassOpDef__OpAssignment_1_0_0");
					put(grammarAccess.getEClassOpDefAccess().getOpAssignment_1_0_1(), "rule__EClassOpDef__OpAssignment_1_0_1");
					put(grammarAccess.getEClassOpDefAccess().getOpAssignment_1_0_2(), "rule__EClassOpDef__OpAssignment_1_0_2");
					put(grammarAccess.getEClassOpDefAccess().getRefAssignment_1_2(), "rule__EClassOpDef__RefAssignment_1_2");
					put(grammarAccess.getEClassOpDefAccess().getSettersAssignment_1_7_1_0(), "rule__EClassOpDef__SettersAssignment_1_7_1_0");
					put(grammarAccess.getEClassOpDefAccess().getAttributesAssignment_1_7_1_1(), "rule__EClassOpDef__AttributesAssignment_1_7_1_1");
					put(grammarAccess.getEClassOpDefAccess().getReferencesAssignment_1_7_1_2(), "rule__EClassOpDef__ReferencesAssignment_1_7_1_2");
					put(grammarAccess.getEAttributeOpDefAccess().getVarAssignment_0_1(), "rule__EAttributeOpDef__VarAssignment_0_1");
					put(grammarAccess.getEAttributeOpDefAccess().getOpAssignment_1_0_0_0(), "rule__EAttributeOpDef__OpAssignment_1_0_0_0");
					put(grammarAccess.getEAttributeOpDefAccess().getOpAssignment_1_0_0_1(), "rule__EAttributeOpDef__OpAssignment_1_0_0_1");
					put(grammarAccess.getEAttributeOpDefAccess().getOpAssignment_1_0_0_2(), "rule__EAttributeOpDef__OpAssignment_1_0_0_2");
					put(grammarAccess.getEAttributeOpDefAccess().getRefAssignment_1_0_2(), "rule__EAttributeOpDef__RefAssignment_1_0_2");
					put(grammarAccess.getEAttributeOpDefAccess().getSettersAssignment_1_3_0_1(), "rule__EAttributeOpDef__SettersAssignment_1_3_0_1");
					put(grammarAccess.getEReferenceOpDefAccess().getVarAssignment_0_1(), "rule__EReferenceOpDef__VarAssignment_0_1");
					put(grammarAccess.getEReferenceOpDefAccess().getOpAssignment_1_0_0_0(), "rule__EReferenceOpDef__OpAssignment_1_0_0_0");
					put(grammarAccess.getEReferenceOpDefAccess().getOpAssignment_1_0_0_1(), "rule__EReferenceOpDef__OpAssignment_1_0_0_1");
					put(grammarAccess.getEReferenceOpDefAccess().getOpAssignment_1_0_0_2(), "rule__EReferenceOpDef__OpAssignment_1_0_0_2");
					put(grammarAccess.getEReferenceOpDefAccess().getRefAssignment_1_0_2(), "rule__EReferenceOpDef__RefAssignment_1_0_2");
					put(grammarAccess.getEReferenceOpDefAccess().getSettersAssignment_1_3_1(), "rule__EReferenceOpDef__SettersAssignment_1_3_1");
					put(grammarAccess.getSetterDefAccess().getMetafeatureAssignment_1(), "rule__SetterDef__MetafeatureAssignment_1");
					put(grammarAccess.getSetterDefAccess().getOperatorAssignment_2(), "rule__SetterDef__OperatorAssignment_2");
					put(grammarAccess.getSetterDefAccess().getParAssignment_3(), "rule__SetterDef__ParAssignment_3");
					put(grammarAccess.getSetterDefAccess().getParAssignment_4_1(), "rule__SetterDef__ParAssignment_4_1");
					put(grammarAccess.getRewritingRuleAccess().getMigratorsSXAssignment_0_0(), "rule__RewritingRule__MigratorsSXAssignment_0_0");
					put(grammarAccess.getRewritingRuleAccess().getMigratorDXAssignment_0_2(), "rule__RewritingRule__MigratorDXAssignment_0_2");
					put(grammarAccess.getRewritingRuleAccess().getMigratorSXAssignment_1_1(), "rule__RewritingRule__MigratorSXAssignment_1_1");
					put(grammarAccess.getRewritingRuleAccess().getMigratorDXAssignment_1_3(), "rule__RewritingRule__MigratorDXAssignment_1_3");
					put(grammarAccess.getMigratorSXAccess().getNameAssignment_1(), "rule__MigratorSX__NameAssignment_1");
					put(grammarAccess.getMigratorSXAccess().getElementSXAssignment_3(), "rule__MigratorSX__ElementSXAssignment_3");
					put(grammarAccess.getMigratorSXAccess().getFilterSXAssignment_6(), "rule__MigratorSX__FilterSXAssignment_6");
					put(grammarAccess.getMigratorSXAccess().getFilterSXAssignment_7_1(), "rule__MigratorSX__FilterSXAssignment_7_1");
					put(grammarAccess.getMigratorDXAccess().getNameAssignment_0_1_0(), "rule__MigratorDX__NameAssignment_0_1_0");
					put(grammarAccess.getMigratorDXAccess().getElementDXAssignment_0_1_2(), "rule__MigratorDX__ElementDXAssignment_0_1_2");
					put(grammarAccess.getMigratorDXAccess().getFilterDXAssignment_0_1_4(), "rule__MigratorDX__FilterDXAssignment_0_1_4");
					put(grammarAccess.getMigratorDXAccess().getFilterDXAssignment_0_1_5_1(), "rule__MigratorDX__FilterDXAssignment_0_1_5_1");
					put(grammarAccess.getFilterMigratorAccess().getFeatureSXAssignment_0(), "rule__FilterMigrator__FeatureSXAssignment_0");
					put(grammarAccess.getFilterMigratorAccess().getOpAssignment_1(), "rule__FilterMigrator__OpAssignment_1");
					put(grammarAccess.getFilterMigratorAccess().getValueAssignment_2(), "rule__FilterMigrator__ValueAssignment_2");
					put(grammarAccess.getDotNavigationObjSXAccess().getObjAssignment_1(), "rule__DotNavigationObjSX__ObjAssignment_1");
					put(grammarAccess.getDotNavigationObjSXAccess().getRefAssignment_2_1(), "rule__DotNavigationObjSX__RefAssignment_2_1");
					put(grammarAccess.getDotNavigationObjDXAccess().getObjAssignment_1(), "rule__DotNavigationObjDX__ObjAssignment_1");
					put(grammarAccess.getDotNavigationObjDXAccess().getRefAssignment_2_1(), "rule__DotNavigationObjDX__RefAssignment_2_1");
					put(grammarAccess.getParameterAccess().getNameAssignment_1(), "rule__Parameter__NameAssignment_1");
					put(grammarAccess.getPackageAccess().getNameAssignment_1(), "rule__Package__NameAssignment_1");
					put(grammarAccess.getClassAccess().getNameAssignment_1(), "rule__Class__NameAssignment_1");
					put(grammarAccess.getAttributeAccess().getNameAssignment_1(), "rule__Attribute__NameAssignment_1");
					put(grammarAccess.getReferenceAccess().getNameAssignment_1(), "rule__Reference__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			it.univaq.coevolution.emfmigrate.ui.contentassist.antlr.internal.InternalEmigParser typedParser = (it.univaq.coevolution.emfmigrate.ui.contentassist.antlr.internal.InternalEmigParser) parser;
			typedParser.entryRuleMyModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public EmigGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EmigGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
