<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="migration"
    nsURI="http://www.univaq.it/coevolution/Migration" nsPrefix="migration">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//PackageOp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operators" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//ComplexOperator"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MigrationProgr" eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//MigrationProgram"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="packageSetters">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metafeature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueRef" unique="false"
        upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="packageSetters_def">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metafeature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="par" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="setNsUri">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nsURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="setNsUri_def">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nsUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="setNsPrefix">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nsPrefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="setNsPrefix_def">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nsPrefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CHANGEPACKAGE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADDPACKAGE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DELETEPACKAGE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageOp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="op" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="setters" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//packageSetters"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//ClassOp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="complex" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//CallOperator"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opdef" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//ENamedElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="settersdef" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="complex" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//ComplexOperator"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="string" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dst" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FeatureSettersdef" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//featureSetters_def"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CHANGECLASS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADDCLASS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DELETECLASS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="classSetter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metafeature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueRef" unique="false"
        upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="classSetters_def">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metafeature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="par" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassOp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="op" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="setters" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//classSetter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//AttributeOp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//ReferenceOp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="complex" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//CallOperator"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="eStructuralFeatureOp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="op" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="setters" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//FeatureSetters"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="complex" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//CallOperator"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CHANGEATTRIBUTE">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refAttr" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADDATTRIBUTE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DELETEATTRIBUTE">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refAttr" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RENAMEATTRIBUTE">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refAttr" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MOVEATTRIBUTE">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refAttr" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dst" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureSetters">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metafeature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueEString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueEInt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueEBool" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueRef" unique="false"
        upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueFeature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeOp" eSuperTypes="platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//eStructuralFeatureOp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CHANGEREFERENCE">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refRef" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADDREFERENCE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DELETEREFERENCE">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refRef" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MOVEREFERENCE">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refRef" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dst" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="featureSetters_def">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClassifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//ENamedElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceOp" eSuperTypes="platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//eStructuralFeatureOp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CHANGE_op" eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//CHANGEREFERENCE"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexOperator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classOperations" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//ClassOp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeOperations" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//AttributeOp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceOperations" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//ReferenceOp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="INT">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="STRING">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EBoolPar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallOperator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fun" eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//ComplexOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//Argument"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Argument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MigrationProgram">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libs" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="migr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformationPackage"
        unique="false" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//Rule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//OpDef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rewritingRules" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//RewritingRule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RewritingRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="migratorsSX" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//MigratorSX"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="migratorDX" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//MigratorDX"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="migratorSX" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//MigratorSX"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MigratorSX">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementSX" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterSX" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//FilterMigrator"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MigratorDX">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementDX" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterDX" upperBound="-1"
        eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//FilterMigrator"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilterMigrator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalFeature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="op" eType="ecore:EClass platform:/resource/it.univaq.coevolution.emfmigrate/src-gen/it/univaq/coevolution/Migration.ecore#//STRING"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dxobj" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dxgetters" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="Classifier" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EClassifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="EReferencePar" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="EAttributePar" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="EClassPar" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="EPackagePar" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
</ecore:EPackage>
