/*
 * generated by Xtext
 */
package it.univaq.coevolution.emfmigrate.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EmigExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return it.univaq.coevolution.emfmigrate.ui.internal.EmigActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return it.univaq.coevolution.emfmigrate.ui.internal.EmigActivator.getInstance().getInjector("it.univaq.coevolution.emfmigrate.Emig");
	}
	
}
